### PR TITLE
Feature/juan/persist detail screen content

### PR DESCRIPTION
**Pull request by juancoob**
**ISSUES**
#36

**SUMMARY**
Persist the detail screen on configuration changes

### CODE REVIEW

**Review by jujoru — APPROVED** [review]
Ok¡

**Review by JorgeGreek — APPROVED** [review]
ok

**Review by joseantoniocampillo — APPROVED** [review]
I think that perhaps it is not the most appropriate to do a merge from a branch that corrects a bug unrelated to the proposal of this PR. I think that the most correct thing would have been to take the branch 'bugFixes / juan / remote-mediator-improvement' to develop through a PR for exclusive purpose and leave the PR Feature / juan / persist detail screen content better limited in its responsibility.

**Comment by juancoob** [comment]
> I think that perhaps it is not the most appropriate to do a merge from a branch that corrects a bug unrelated to the proposal of this PR. I think that the most correct thing would have been to take the branch 'bugFixes / juan / remote-mediator-improvement' to develop through a PR for exclusive purpose and leave the PR Feature / juan / persist detail screen content better limited in its responsibility.

Yes, next time I'll scope better the PR limit

**Pull request merged**
