### PR TITLE
Feature/migrate main activity to mvvm databinding

### PR DESCRIPTION
**Pull request by juancoob**
**ISSUE**
#44

**SUMMARY**
Adapt the main list to use MVVM with Databinding and Navigation

**CHANGES MADE**

Add navigation, databinding and safeArgs libraries.

Attach the progressBar binding adapter for the MainActivity view. It controls when the progressBar is loading.

Append the setItem binding adapter for the MainActivity view.

Adapt MainViewModel to the MVVM needs.

Update MainActivity and its layout to apply Databinding.

Update extensions functions for fragments.

Pass context to the Repository because it is easier to get from the binding.

Add fitsystemwindows to see the content under the toolbar.

Upgrade MainActivity to MainFragment to use Navigation.

Update MainViewModel to remove unnecessary functions. Now the selected view is passed on a function as a lambda.

Remove the transition name from the hero item because it is added dynamically.

Remove the transition name from fragment_hero_detail because it is added dynamically.

Add the transition name to the AdapterList to show the animation.

Update HeroDetailActivity to HeroDetailFrament to use Navigation.

**TEST CHANGES**
Open the app and check the navigation between the list to the detail

### CODE REVIEW

**Review by jujoru — APPROVED** [review]
Ok ¡

**Review by joseantoniocampillo — CHANGES_REQUESTED** [review]
At this point we must delete secret.properties file for do not get in checkout to this branch.

**Comment by juancoob** [comment]
> At this point we must delete secret.properties file for do not get in checkout to this branch.

@joseantoniocampillo what do you mean? There is no secret.properties file on this PR. Do you mean to merge your changes and remove the dummy secret properties from the repository?

**Review by joseantoniocampillo — APPROVED** [review]
That's ok

**Pull request merged**
