### PR TITLE
Feature/juan/biometric

### PR DESCRIPTION
**Pull request by juancoob**
**ISSUE**
#65 

**SUMMARY**
Created a flow that uses the biometric login to unlock the favourite character list

### CODE REVIEW

**Review by jujoru — APPROVED** [review]
Ok

**Review by JorgeGreek — APPROVED** [review]
ok

**Review by joseantoniocampillo — APPROVED** [review]
Personally I would like more that in the BiometricDataSource implementation it will not call Toast. I also think that the use case could be simplified and it is not necessary to expose the check in the activity. I have left it as in my opinion it seems cleaner and simpler ([this way](https://github.com/Architect-Coders-Team-2/ArquitectoMarvel/tree/feature/jose/biometricUseCase-simpler)). However I approve and consider it to be a good job

**Comment by joseantoniocampillo** [comment]
I have restored branch to see differences with the propose indicated in my approved message for revision about this PR

**Pull request merged**
