### PR TITLE
Current state for develop branch in a simple mvp perspective

### PR DESCRIPTION
**Pull request by joseantoniocampillo**
Without further evolution for the current state of the code in develop branch. A simple mvp approach to managing the only screen present at the moment (MainActivity)

### CODE REVIEW

**Review by juancoob — APPROVED** [review]
Approved!

**Review by JorgeGreek — APPROVED** [review]
οκ

**Review by eleazan — APPROVED** [review]
Nice

**Review by jujoru — COMMENTED** [review]
Ok !

**Pull request merged**
